# Generated by Django 2.2.6 on 2022-12-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_procurement', '0003_auto_20221216_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contractor',
            field=models.ManyToManyField(to='public_procurement.TheContractor'),
        ),
    ]
