# Generated by Django 2.2.6 on 2022-12-16 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public_procurement', '0004_auto_20221216_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='type',
        ),
        migrations.AddField(
            model_name='typeprocurement',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='public_procurement.Contract'),
        ),
    ]
