# Generated by Django 4.1.2 on 2022-12-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_procurement', '0005_auto_20221216_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='thecontractor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='typeprocurement',
            name='contract',
        ),
        migrations.AlterField(
            model_name='typeprocurement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='typeprocurement',
            name='contract',
            field=models.ManyToManyField(to='public_procurement.contract'),
        ),
    ]
